-- Create the database
CREATE DATABASE IF NOT EXISTS if0_39196567_COS30043_Project;
USE if0_39196567_COS30043_Project;

-- Drop and recreate users table
DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
